### ISSUE TITLE
Consult about the D2Q9 velocity sets

### ISSUE THREAD

**Issue by tsq9** [vikram8128/PythonLatticeBoltzmann#1]
Dear Singh, your work is very helpful for me to understand the LBM. I plan to apply your code to simulate the fluid flow under a complex boundary. If you could supply the structure of the D2Q9 velocity sets in your code, it will be easier for me to develop my model based on your code.

Is the D2Q9 velocity sets like
row0 = [2,5,8]
row1 = [1,4,7]
row2 = [0,3,6]
or
row2 = [0,3,6]
row1 = [1,4,7]
row0 = [2,5,8] ?
And what is the relation between the different numbers with the 
v = [[ 1  1] [ 1  0] [ 1 -1] [ 0  1] [ 0  0] [ 0 -1] [-1  1] [-1  0] [-1 -1]] ?
Is row0 = [2,5,8] and row0 = [ 1  1] [ 1  0] [ 1 -1] or row0 = [2,5,8] and row0 = [-1  1] [-1  0] [-1 -1] ?

Thank you very much for your contribution. I am new to LBM, and I have obtained good primary achievements through modifying your code. I am looking forward to your reply.

**Comment by vikram8128** [comment]
Hi tsq9, thanks for your interest in this project.

The velocity sets are like:
```
row0 = array([2,5,8])
row1 = array([1,4,7])
row2 = array([0,3,6])
```

The velocity sets and the corresponding directions are defined in this function:
```
def genV() :
    v = []
    for x in range(qDim,-qDim-1,-1) :
        for y in range(qDim,-qDim-1,-1) :
            v.append([x,y])
    return v
```
This gives that `row0` corresponds to `[1 -1] [0 -1] [-1 -1]`.

However, these are just arbitrary choices, and are not too important to the algorithm. If for some reason they do not line up with your requirements, it is possible to switch this, you would have to edit the code defining inflow and outflow, as well as creating maps from images.

Hope this helps.

**Comment by tsq9** [comment]
Thank you very much for your help, I have understood your code and completed my task based on your work. Best wish.
